import {structureDetails,toolDetails,inventoryRows} from './inspection.js';
import {structSprite} from './structs.js';
import {manSprite} from './people.js';
import {rigSprite} from './rig.js';
const esc=n=>String(n).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function setupInspection(cv,V,getWorld){
  const style=document.createElement('style');style.textContent=`
  #inspection{position:fixed;inset:0;z-index:10;color-scheme:light}#inspection[hidden]{display:none}
  .inspect-shade{position:absolute;inset:0;background:#27352d33}.inspect-paper{position:absolute;left:max(10px,env(safe-area-inset-left));right:max(10px,env(safe-area-inset-right));bottom:calc(12px + env(safe-area-inset-bottom));max-width:480px;margin:auto;max-height:76dvh;max-height:76vh;display:flex;flex-direction:column;border:1px solid #a69267;border-radius:20px;background:#f4efda;color:#433925;box-shadow:0 12px 40px #27352d66;font:15px/1.45 system-ui;touch-action:pan-y;user-select:text;-webkit-user-select:text}
  .inspect-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:18px 20px 12px}.inspect-head h2{font:500 25px/1.15 Georgia;margin:5px 0;text-transform:capitalize}.inspect-close,.inspect-back{min-width:44px;min-height:44px;border:0;border-radius:50%;background:#e7dfc5;color:#68553b;font:24px system-ui;cursor:pointer}.inspect-scroll{overflow:auto;padding:0 20px 22px;overscroll-behavior:contain;-webkit-overflow-scrolling:touch}.inspect-picture{width:100%;height:146px;display:block;image-rendering:pixelated;background:#d9dfba;border:1px solid #cbd0aa;border-radius:12px;margin-bottom:16px}
  .inspect-paper h3{font:600 13px system-ui;color:#6e7852;margin:22px 0 8px}.inspect-row{display:flex;justify-content:space-between;gap:14px;padding:10px 0;border-bottom:1px solid #ded6bb}.inspect-row span:last-child{text-align:right;color:#7b6b50}.inspect-list button{display:flex;width:100%;justify-content:space-between;align-items:center;gap:12px;min-height:48px;border:0;border-bottom:1px solid #ded6bb;background:transparent;color:#433925;text-align:left;font:15px system-ui;cursor:pointer}.inspect-list button span:last-child{font:12px system-ui;color:#7b6b50;text-align:right}.inspect-note{font:12px/1.5 system-ui;color:#897b60;margin:14px 0 0}.inspect-link{min-height:44px;border:1px solid #b9b991;border-radius:10px;background:#e2e6cc;color:#4e5f3f;font:600 13px system-ui;padding:10px 14px;cursor:pointer}.inspect-material small{display:block;color:#897b60;font-size:11px}.inspect-choice{border-left:3px solid #bbc39b;padding:6px 10px;margin:8px 0;font-size:13px}.inspect-choice small{display:block;color:#897b60;margin-top:3px}`;
  document.head.append(style);const root=document.createElement('div');root.id='inspection';root.hidden=true;document.body.append(root);
  let target=null,lastFocus=null,lastWorld=null,lastMinute=-1,inert=[];
  function close(){root.hidden=true;target=null;for(const [el,old]of inert)el.inert=old;inert=[];if(lastFocus?.isConnected)lastFocus.focus();}
  function show(next){if(root.hidden){lastFocus=document.activeElement;inert=[...document.body.children].filter(el=>el!==root).map(el=>[el,el.inert]);for(const [el]of inert)el.inert=true;}target=next;root.hidden=false;draw();root.querySelector('.inspect-close').focus();}
  const rows=list=>list.map(q=>`<div class="inspect-row"><span>${esc(q.label)}</span><span>${esc(q.value)}</span></div>`).join('');
  const materials=list=>list.map(q=>`<div class="inspect-row inspect-material"><span>${esc(q.label)}${q.condition?`<small>${esc(q.condition)}</small>`:''}</span><span>${esc(q.value)}</span></div>`).join('');
  function draw(){const W=getWorld(),M=W.man;lastWorld=W;lastMinute=W.t;let title,body,sp=null;
    if(target.sid!=null){const s=W.structs.find(s=>s.id===target.sid);if(!s){close();return;}const d=structureDetails(s);title=d.title;sp=structSprite(s);
      body=rows(d.fields)+(d.materials.length?'<h3>Installed materials</h3>'+materials(d.materials):'<p class="inspect-note">The site is waiting for its first parts.</p>')+(d.onsite.length?'<h3>Brought to the site</h3>'+rows(d.onsite):'');
      if(d.comparison){body+='<h3>Why this design?</h3><p class="inspect-note">He compared '+d.comparison.alternatives+' possible assemblies. These were his estimates when he chose it.</p>'+d.comparison.choices.map((q,i)=>`<div class="inspect-choice">${i===0?'Chosen':'Alternative'}: ${esc(q.cover||'open frame')}<small>About ${Math.round(q.labourMinutes)} minutes of work · ${Math.round(q.predictedKg)} kg estimated extra load${q.protection>0?' · '+Math.round(q.protection*100)+'% rain kept off the surface':''}</small></div>`).join('');}
      body+='<p class="inspect-note">Shown from the parts actually installed. Strength and protection are simplified estimates; damage and wetness change them.</p>';
    }else if(target.tool){const d=toolDetails(M,target.tool);title=d.title;body=rows(d.fields)+'<h3>The working parts</h3>'+materials(d.materials)+`<p class="inspect-note">${target.tool==='line'?'The pull limit describes a steady load. A sudden tug can break a line sooner.':'Wear blunts the stone edge. Damp fibres weaken its binding.'}</p>`;sp=rigSprite({stance:'stand',tool:target.tool,work:[6,-14],motion:'rest',period:1000,frames:1,key:'inspect:'+target.tool,toolLength:M.tools?.[target.tool]?.parts.find(p=>p.kind==='handle')?.length},0);
    }else{title=target.camp?'Camp & belongings':'With Tomas';sp=manSprite('stand',0,M);const items=inventoryRows(M);
      body=`<p class="inspect-note">${target.camp?'His constructions and the things he has with him.':'The things he has with him now.'}</p><div class="inspect-list">`+items.map(q=>q.tool?`<button data-tool="${q.key}"><span>${esc(q.label)}</span><span>Inspect →</span></button>`:`<div class="inspect-row"><span>${esc(q.label)}</span><span>${esc(q.value)}</span></div>`).join('')+(items.length?'':'<p>His hands are empty for now.</p>')+'</div>';
      if(target.camp)body+='<h3>Made on the island</h3><div class="inspect-list">'+W.structs.map(s=>`<button data-sid="${s.id}"><span>${esc(structureDetails(s).title)}</span><span>${s.stage>=s.stages.length?'Complete':'Under way'} →</span></button>`).join('')+'</div>';
      else body+='<p><button class="inspect-link" data-camp>See his camp</button></p>';
    }
    root.innerHTML=`<div class="inspect-shade"></div><section class="inspect-paper" role="dialog" aria-modal="true" aria-labelledby="inspect-title"><header class="inspect-head">${target.sid!=null||target.tool?'<button class="inspect-back" aria-label="Back to belongings">‹</button>':''}<div style="flex:1"><span class="eyebrow">THE CASTAWAY</span><h2 id="inspect-title">${esc(title)}</h2></div><button class="inspect-close" aria-label="Close inspection">×</button></header><div class="inspect-scroll">${sp?'<canvas class="inspect-picture" aria-label="The object as it looks now"></canvas>':''}${body}</div></section>`;
    root.querySelector('.inspect-close').onclick=close;root.querySelector('.inspect-shade').onclick=close;root.querySelector('.inspect-back')?.addEventListener('click',()=>show({camp:true}));root.querySelector('[data-camp]')?.addEventListener('click',()=>show({camp:true}));
    for(const b of root.querySelectorAll('[data-sid]'))b.onclick=()=>show({sid:+b.dataset.sid});for(const b of root.querySelectorAll('[data-tool]'))b.onclick=()=>show({tool:b.dataset.tool});
    const picture=root.querySelector('canvas');if(picture&&sp){picture.width=360;picture.height=146;const g=picture.getContext('2d');g.imageSmoothingEnabled=false;g.fillStyle='#d9dfba';g.fillRect(0,0,360,146);
      const w=sp.img.width,h=sp.img.height,pixels=sp.img.getContext('2d').getImageData(0,0,w,h).data;let left=w,right=-1,top=h,bottom=-1;
      for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(pixels[(y*w+x)*4+3]){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}
      if(right>=left){const scale=w/(sp.w||w),cw=right-left+1,ch=bottom-top+1,k=Math.max(1,Math.min(3,Math.floor(Math.min(330/(cw/scale),130/(ch/scale))))),dw=cw/scale*k,dh=ch/scale*k;g.drawImage(sp.img,left,top,cw,ch,Math.round((360-dw)/2),Math.round((146-dh)/2),dw,dh);}}
  }
  document.addEventListener('keydown',e=>{if(root.hidden)return;if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const bs=[...root.querySelectorAll('button')],i=bs.indexOf(document.activeElement);if(e.shiftKey&&i<=0){e.preventDefault();bs.at(-1).focus();}else if(!e.shiftKey&&(i<0||i===bs.length-1)){e.preventDefault();bs[0].focus();}}},true);
  const down=new Map();cv.addEventListener('pointerdown',e=>{if(down.size){for(const p of down.values())p.cancel=true;}down.set(e.pointerId,{x:e.clientX,y:e.clientY,time:e.timeStamp,cancel:down.size>0});});
  cv.addEventListener('pointermove',e=>{const p=down.get(e.pointerId);if(p&&Math.hypot(e.clientX-p.x,e.clientY-p.y)>10)p.cancel=true;});cv.addEventListener('pointercancel',e=>down.delete(e.pointerId));
  cv.addEventListener('pointerup',e=>{const p=down.get(e.pointerId);down.delete(e.pointerId);if(!p||p.cancel||e.timeStamp-p.time>600)return;
    const rect=cv.getBoundingClientRect(),raster=V.raster||1,snap=n=>Math.round(n*raster)/raster,sx=snap(V.cam.x-V.aw/2),sy=snap(V.cam.y-V.ah/2),x=(e.clientX-rect.left)*V.aw/rect.width+sx,y=(e.clientY-rect.top)*V.ah/rect.height+sy,W=getWorld(),m=V.manPos(performance.now());
    if(Math.abs(x-m.x*16)<11&&y>m.y*16-30&&y<m.y*16+7){show({});return;}
    for(const s of W.structs.slice().sort((a,b)=>b.y-a.y)){const sp=structSprite({...s,open:Math.abs(s.x-W.man.x)<.7&&Math.abs(s.y-W.man.y)<.7});if(!sp)continue;const a=Math.floor(x-(Math.round(s.x*16)-sp.ox)),b=Math.floor(y-(Math.round(s.y*16)+5-sp.oy));if(a<0||b<0||a>=sp.img.width||b>=sp.img.height)continue;const px=sp.img.getContext('2d').getImageData(Math.max(0,a-2),Math.max(0,b-2),Math.min(5,sp.img.width-a),Math.min(5,sp.img.height-b)).data;if(px.some((n,k)=>k%4===3&&n)){show({sid:s.id});break;}}
  });
  return{show,close,refresh(){if(target&&(lastWorld!==getWorld()||lastMinute!==getWorld().t)){const scroll=root.querySelector('.inspect-scroll')?.scrollTop||0,a=document.activeElement,key=a?.dataset.sid?`[data-sid="${a.dataset.sid}"]`:a?.dataset.tool?`[data-tool="${a.dataset.tool}"]`:a?.classList.contains('inspect-back')?'.inspect-back':'.inspect-close';draw();const el=root.querySelector('.inspect-scroll');if(el)el.scrollTop=scroll;if(!root.hidden)root.querySelector(key)?.focus({preventScroll:true});}}};
}
