import assert from 'node:assert/strict';
import {compareDesigns,propose} from '../src/build/designer.js';
import {createWorld,save,load} from '../src/sim/world.js';
import {SEED,BORN} from '../src/config.js';
import {place} from '../src/build/build.js';
import {assemblyStep} from '../src/build/assembly.js';
const b={skill:1,cover:'bracken',knows:{reeds:true}},need={storageKg:5,dry:.85},opts=compareDesigns(need,b,{rain:2});
assert(opts.some(q=>q.cover==='reeds'));assert(opts.some(q=>q.cover==='bracken'));assert(!opts.some(q=>q.cover==='boughs'));
for(let n=1;n<opts.length;n++)assert(opts[n].score>=opts[n-1].score);
const dry=propose(need,b,{}),rain=propose(need,b,{rain:4,gust:25});assert(rain.comparison.choices[0].requiredKg>dry.comparison.choices[0].requiredKg);
const reedsFar=propose(need,{...b,gatherMins:{reeds:1000,bracken:1}},{}),brackenFar=propose(need,{...b,gatherMins:{reeds:1,bracken:1000}},{});
assert.equal(reedsFar.comparison.choices[0].cover,'bracken');assert.equal(brackenFar.comparison.choices[0].cover,'reeds');
const stocked=compareDesigns(need,{...b,stock:{poles:100,withies:100,bracken:100,reeds:100}},{});
assert(stocked[0].labourMinutes<dry.comparison.choices[0].labourMinutes);
const W=createWorld(SEED,BORN),M=W.man,a=propose({bench:.9},b,{}),stages=a.stages;delete a.stages;
const s=place(W,{k:'workbench',x:M.x,y:M.y,dir:0,assembly:a,stages});s.stage=stages.length;
W.wx={...W.wx,gust:0,rain:0};W.surface.snow=0;assemblyStep(W,s);assert(Object.values(M.constructionMemory).some(q=>q.carriedN>0));
const remembered=JSON.stringify(M.constructionMemory);M.x+=20;assemblyStep(W,s);assert.equal(JSON.stringify(M.constructionMemory),remembered);
assert.equal(save(load(save(W))),save(W));
const before=save(W);compareDesigns(need,b,W.wx);assert.equal(save(W),before);
console.log('ok   deterministic comparisons use known covers, collection effort, owned stock, weather loads and witnessed trials; saved estimates grant no physical abilities');
