import assert from 'node:assert/strict';
import {createWorld,save,load} from '../src/sim/world.js';
import {SEED,BORN} from '../src/config.js';
import {axeDesign,lineDesign,toolProps,makeTool,ensureTools,useAxe,useLine,woodWorkRate,toolMass} from '../src/sim/tools.js';
import {ACTIONS} from '../src/mind/actions.js';
const near=(a,b)=>assert(Math.abs(a-b)<1e-9,`${a} != ${b}`),W=createWorld(SEED,BORN),M=W.man;
const axe=axeDesign(1),p=toolProps(axe);near(p.energy,.5*.9*4**2);
const handle=axe.parts[1],r=Math.sqrt(handle.kg/(650*Math.PI*handle.length));near(p.handleN,24e6*Math.PI*r**3/(4*handle.length));
const line=lineDesign(.8),q=toolProps(line);near(q.tension,Math.PI*.003**2/4*4e6*.8);
assert(q.tension>0);line.parts[0].kg/=2;near(toolProps(line).tension,q.tension/2);
console.log('ok   strike energy, handle bending strength and fibre tensile force match independent SI equations');
M.inv={axe:1,line:1};makeTool(M,'axe');makeTool(M,'line');const mass=toolMass(M),speed=woodWorkRate(M);assert(speed>1);
for(let n=0;n<500;n++)useAxe(M,1,{rain:0});assert(woodWorkRate(M)<speed);near(toolMass(M),mass);assert(M.toolDustKg>0);
const strength=toolProps(M.tools.line).tension;assert(useLine(M,10,strength*.9));near(toolMass(M),mass);
assert(!useLine(M,0,strength*2));assert.equal(M.inv.line,0);near(toolMass(M),mass);assert(M.brokenTools.length);
const binding=M.tools.axe.parts.find(p=>p.kind==='binding');binding.condition=.000001;useAxe(M,20,{rain:10});assert.equal(M.inv.axe,0);near(toolMass(M),mass);
console.log('ok   wear reduces usefulness, overloading breaks the actual part, and dust plus retained fragments conserve tool mass');
const fresh=createWorld(SEED,BORN),F=fresh.man;F.inv={stones:2,poles:1,cord:2};let state={};
for(let n=0;n<15;n++)ACTIONS.haftAxe.exec(fresh,F,{x:null},state);assert(F.workpieces.axe.paid);assert.equal(F.inv.stones,0);
const resumed=load(save(fresh));state={};for(let n=0;n<150;n++)if(ACTIONS.haftAxe.exec(resumed,resumed.man,{x:null},state)==='done')break;
assert(resumed.man.inv.axe);near(toolMass(resumed.man),4+1.5+.18);assert(resumed.man.toolScraps.stones>0);
assert(save(load(save(resumed)))===save(resumed));
console.log('ok   paid tool work resumes across checkpoints, charges once, and retains every kilogram as a useful part or offcut');
const branch={id:fresh.nextId++,k:'branch',x:F.x,y:F.y,kg:1.2};fresh.items.push(branch);F.inv={};state={};
for(let n=0;n<30;n++)if(ACTIONS.get_poles.exec(fresh,F,{...branch,key:'i'+branch.id,tile:Math.floor(F.y)*fresh.MW+Math.floor(F.x)},state)==='done')break;
near(F.inv.poles*1.5,1.2);assert(!fresh.items.includes(branch));
console.log('ok   a short branch yields only its actual mass of poles; gathering does not invent missing wood');
