import assert from 'node:assert/strict';
import {createWorld,save,load} from '../src/sim/world.js';
import {SEED,BORN} from '../src/config.js';
import {FAMILIES,place,propsOf,work} from '../src/build/build.js';
import {channelDischarge,weirDischarge,hydroTen,waterVolume,mineralMass,takeCollectedWater,SILT_V} from '../src/sim/hydro.js';
import {dexp} from '../src/core/dmath.js';
const W=createWorld(SEED,BORN),near=(a,b,tol=1e-5)=>assert(Math.abs(a-b)<tol,`${a} != ${b}`);
assert.equal(channelDischarge(.3,.1,2,0),0);assert.equal(weirDischarge(.7,-.1),0);
const q=channelDischarge(1,1,1,1,.05);near(q,(1/3)**(2/3)/.05,1e-10);
near(channelDischarge(1,1,1,4,.05),q*2);near(weirDischarge(1,.4)/weirDischarge(1,.1),8);
console.log('ok   Manning discharge and broad-crested overflow match independent equations and head scaling');
W.wx={...W.wx,rain:0,temp:10,sun:0,wind:0,hum:1};W.surface.temp=10;
const i=W.hydroMap.land.find(i=>W.hydroMap.down[i]>=0&&W.ter[W.hydroMap.down[i]]>1),j=W.hydroMap.down[i];
const heights=[W.h[i],W.h[j]];W.h[i]=W.h[j]=.4;const make=k=>{const stages=FAMILIES[k].make({}),s=place(W,{k,x:i%W.MW+.5,y:Math.floor(i/W.MW)+.5,dir:0,stages});for(const st of stages){Object.assign(s.onsite,st.need);work(W,s,1);}s.props=propsOf(s);return s;};
const weir=make('weir');W.hydro.pool[i]=.25;hydroTen(W);assert.equal(weir.flow,0,'water below a stone crest cannot flow uphill over it');
W.hydro.pool[i]=1;hydroTen(W);assert(weir.flow>0);assert(W.hydro.pool[i]>=weir.props.crest*4-1e-6);
const waterBalance=()=>waterVolume(W)+W.hydro.evap+W.hydro.used+W.hydro.sea-W.hydro.rain;
W.h[i]=heights[0];W.h[j]=heights[1];W.structs=[];
const pit=make('settlingPool');W.hydro.pool[i]=.2;W.hydro.silt[i]=.1;
const water=waterBalance(),minerals=mineralMass(W);
for(let n=0;n<60;n++)hydroTen(W);
near(waterBalance(),water,1e-7);near(mineralMass(W),minerals);
assert(pit.waterL>0&&pit.waterL<=pit.props.capacity);assert(pit.depositedKg>0);assert(pit.spoilKg>0);assert(pit.waterLoad>=2);
const volume=pit.props.capacity;pit.depositedKg+=16;pit.spoilKg-=16;pit.props=propsOf(pit);assert(pit.props.capacity<volume-9);
const before=mineralMass(W);takeCollectedWater(W,pit,10000);near(mineralMass(W),before);assert.equal(pit.waterL,0);near(waterBalance(),water,1e-7);
const saved=save(W),restored=load(saved);assert(save(restored)===saved,'save/load must match');
for(let n=0;n<144;n++){hydroTen(W);hydroTen(restored);}assert(save(restored)===save(W),'future must replay exactly');
console.log('ok   crest overflow, finite pits, excavation spoil, erosion, settling, lost capacity and drinking conserve both water and minerals; checkpoint replay is exact');
// A closed settling fixture has the same exact exponential decay at different integration intervals.
let mass=1;for(let n=0;n<60;n++)mass*=dexp(-SILT_V*60/.2);near(mass,dexp(-SILT_V*3600/.2),1e-10);
console.log('ok   Stokes settling matches the analytic one-hour solution independently of interval');
