import * as THREE from 'three/webgpu';
import {ANIM} from '../../v2/src/render/people.js';
import {workPose} from '../../v2/src/render/workpose.js';
import {groundAt,clamp,waterAt} from './model.js';
import {ball,box,material,bar,floatOrientation} from './objects.js';
const up=new THREE.Vector3(0,1,0);
function bone(group,color,r){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r,1,10),material(color));mesh.castShadow=mesh.receiveShadow=true;group.add(mesh);return mesh;}
function fit(mesh,a,b){mesh.position.copy(a).add(b).multiplyScalar(.5);const dir=new THREE.Vector3().subVectors(b,a);mesh.scale.y=dir.length();mesh.quaternion.setFromUnitVectors(up,dir.normalize());}
// Two-bone inverse kinematics with fixed anatomical segment lengths.
export function ik(a,b,l1,l2,bend=1){const d=new THREE.Vector3().subVectors(b,a),length=clamp(d.length(),Math.abs(l1-l2)+1e-5,l1+l2-1e-5),along=(length*length+l1*l1-l2*l2)/(2*length),height=Math.sqrt(Math.max(0,l1*l1-along*along)),unit=d.normalize(),side=new THREE.Vector3(0,unit.z,-unit.y).normalize();return a.clone().addScaledVector(unit,along).addScaledVector(side,height*bend);}
export function along(trail,f,x,y){if(!trail||trail.length<2)return{x,y,dx:0,dy:0,distance:0};let distance=0;for(let i=1;i<trail.length;i++)distance+=Math.hypot(trail[i][0]-trail[i-1][0],trail[i][1]-trail[i-1][1]);let left=distance*f;for(let i=1;i<trail.length;i++){const a=trail[i-1],b=trail[i],d=Math.hypot(b[0]-a[0],b[1]-a[1]);if(left<=d||i===trail.length-1){const t=d?clamp(left/d):0;return{x:a[0]+(b[0]-a[0])*t,y:a[1]+(b[1]-a[1])*t,dx:b[0]-a[0],dy:b[1]-a[1],distance:distance*2};}left-=d;}return{x,y,dx:0,dy:0,distance:0};}
class Human {
 constructor(scene){this.root=new THREE.Group();this.root.userData={kind:'man'};scene.add(this.root);this.torso=ball(this.root,'#527c72',0,1.2,0,.24,.32,.15,2);this.hip=ball(this.root,'#5b4c3b',0,.9,0,.2,.13,.16);this.head=ball(this.root,'#dba580',0,1.68,0,.135,.16,.125,2);this.hair=ball(this.root,'#63442e',0,1.78,-.025,.14,.07,.125,2);this.beard=ball(this.root,'#805736',0,1.61,.065,.10,.065,.075,1);this.nose=ball(this.root,'#d6a07a',0,1.69,.125,.032,.035,.04,1);this.eyes=[ball(this.root,'#2f2b25',-.055,1.72,.109,.012,.011,.009),ball(this.root,'#2f2b25',.055,1.72,.109,.012,.011,.009)];this.legs=Array.from({length:4},()=>bone(this.root,'#625646',.065));this.arms=Array.from({length:4},()=>bone(this.root,'#62887b',.055));this.hands=[ball(this.root,'#dba580',0,0,0,.055,.055,.045),ball(this.root,'#dba580',0,0,0,.055,.055,.045)];this.boots=[box(this.root,'#49372a',0,0,0,.12,.09,.23),box(this.root,'#49372a',0,0,0,.12,.09,.23)];this.toolGroup=new THREE.Group();this.root.add(this.toolGroup);this.toolKey=null;}
 tools(spec,M){const key=spec.tool||'';if(key===this.toolKey)return;this.toolKey=key;while(this.toolGroup.children.length){const m=this.toolGroup.children[0];this.toolGroup.remove(m);m.geometry.dispose();m.material.dispose();}if(['pole','stick','branch','rod','axe'].includes(key)){bar(this.toolGroup,'#a18150',new THREE.Vector3(0,-.12,0),new THREE.Vector3(0,key==='pole'?1.4:key==='rod'?1:.4,0),key==='pole'?.025:.013);if(key==='axe')ball(this.toolGroup,'#929a90',.07,.35,0,.10,.065,.025);}if(key==='basket'||key==='bundle')ball(this.toolGroup,key==='basket'?'#b09563':'#76874d',0,0,.09,.15,.12,.13);if(key==='stone'||key==='stones'||key==='flake')ball(this.toolGroup,'#979d90',0,0,0,.045,.03,.025);if(key==='pot'||key==='clay')ball(this.toolGroup,'#ad7d58',0,-.07,.06,.1,.12,.1);}
 animate(W,seconds,f){const M=W.man,q=along(M.trail,f,M.x,M.y),g=this.root,heading=q.distance>.01?Math.atan2(q.dx,q.dy):g.rotation.y||((M.face||1)*Math.PI/2);g.position.set(q.x*2,groundAt(W,q.x*2,q.y*2),q.y*2);g.rotation.y=heading;g.rotation.z=0;
  const spec={...(ANIM[M.B.asleep?'sleep':M.pose]||ANIM.stand),...workPose(W,M,q)},lying=!M.B.alive||spec.stance==='lie';
  if(lying){g.rotation.z=Math.PI/2;g.position.y+=.22;g.rotation.y=heading;}
  const walking=spec.stance==='walk'&&q.distance>.02&&!lying,phase=walking?seconds*(q.distance/60)/.8*Math.PI*2:seconds*(M.workContact?.t===W.t?M.workContact.frequency||0:1000/(spec.period||4200))*Math.PI*2,s=Math.sin(phase),c=Math.cos(phase),stance=lying?'stand':spec.stance;
  const hip=stance==='sit'?.3:stance==='kneel'||stance==='kneelUp'?.51:stance==='squat'?.46:.91,lean=spec.lean||0,torsoY=hip+.29,headY=hip+.76;
  this.hip.position.y=hip;this.torso.position.set(0,torsoY,lean*.28);this.torso.rotation.x=lean*.45;this.head.position.set(0,headY,lean*.3);this.hair.position.set(0,headY+.10,lean*.3-.025);this.beard.position.set(0,headY-.07,lean*.3+.065);this.nose.position.set(0,headY+.01,lean*.3+.125);for(let n=0;n<2;n++)this.eyes[n].position.set(n?.055:-.055,headY+.04,lean*.3+.109);
  for(let n=0;n<2;n++){const x=n?.12:-.12,footZ=stance==='sit'?.52:stance==='kneel'?n?.18:-.3:walking?s*(n?-.26:.26):n?.08:-.04,footY=walking?Math.max(0,c*(n?1:-1))*.08:0,a=new THREE.Vector3(x,hip,0),b=new THREE.Vector3(x,footY+.05,footZ),k=ik(a,b,.45,.45,1);fit(this.legs[n*2],a,k);fit(this.legs[n*2+1],k,b);this.boots[n].position.set(x,footY+.045,footZ+.04);
   const shoulder=new THREE.Vector3(n?.24:-.24,hip+.5,lean*.27),work=spec.work||[4,-12],hand=new THREE.Vector3(n?.18:-.18,clamp(-work[1]/18,.13,1.55),work[0]/18);if(walking){hand.y=hip+.08;hand.z=s*(n?.18:-.18);}else if(['strike','rub'].includes(spec.motion))hand.y+=Math.max(0,s)*.18;else if(['saw','pull','pick'].includes(spec.motion))hand.z+=s*.07;else if(spec.motion==='mouth'){hand.y+=Math.max(0,s)*(headY-hand.y-.08);hand.z-=Math.max(0,s)*.12;}else if(spec.motion==='wave')hand.y=headY+.16+s*.10;
   const elbow=ik(shoulder,hand,.3,.3,-1);const reach=new THREE.Vector3().subVectors(hand,shoulder);if(reach.length()>.599)hand.copy(shoulder).add(reach.setLength(.599));fit(this.arms[n*2],shoulder,elbow);fit(this.arms[n*2+1],elbow,hand);this.hands[n].position.copy(hand);}
  this.tools(spec,M);this.toolGroup.position.copy(this.hands[1].position);this.toolGroup.rotation.x=spec.motion==='strike'?-.6+Math.max(0,s)*.9:0;this.root.visible=true;this.position=q;
 }
}
function makeAnimal(a){const g=new THREE.Group();g.userData={kind:'animal',id:a.id};const gull=a.sp==='gull',rabbit=a.sp==='rabbit',coat=gull?'#e8e7db':rabbit?'#a5967c':'#b98450';ball(g,coat,0,gull?.18:rabbit?.22:.48,0,gull?.13:rabbit?.15:.2,gull?.12:rabbit?.15:.22,gull?.23:rabbit?.24:.45,2);const head=ball(g,coat,0,gull?.24:rabbit?.33:.66,gull?.20:rabbit?.24:.39,gull?.085:rabbit?.1:.15,gull?.075:rabbit?.11:.16,gull?.10:rabbit?.09:.19,2);if(gull)ball(g,'#d5a348',0,.23,.32,.025,.025,.08);else{ball(g,gull?'#d5a348':'#342b24',0,rabbit?.32:.62,rabbit?.34:.57,.035,.025,.025);for(let n=0;n<2;n++)ball(g,coat,n?.075:-.075,rabbit?.50:.80,rabbit?.19:.32,rabbit?.025:.06,rabbit?.14:.10,.035);}
 const legs=Array.from({length:gull?2:4},()=>bone(g,gull?'#c99544':coat,gull?.012:rabbit?.025:.04));const wings=[];if(gull)for(let n=0;n<2;n++)wings.push(ball(g,'#b9c1bb',n?.27:-.27,.2,-.01,.27,.025,.14));if(a.sp==='dog'){ball(g,'#dfd5c3',0,.54,.28,.15,.13,.13);const collar=new THREE.Mesh(new THREE.TorusGeometry(.11,.012,6,16),material('#c9b481'));collar.position.set(0,.65,.31);collar.rotation.x=Math.PI/2;g.add(collar);}let raft;if(a.adrift){raft=box(g,'#a5834e',0,-.10,0,1.1,.1,1.3);}return{a,g,legs,wings,head,raft};}
export class Actors {
 constructor(scene,W){this.scene=scene;this.human=new Human(scene);this.animals=new Map();this.update(W);}
 update(W){this.W=W;const live=new Set(W.animals.filter(a=>!a.dead&&!a.under).map(a=>a.id));for(const [id,q]of this.animals)if(!live.has(id)){this.scene.remove(q.g);q.g.traverse(m=>{m.geometry?.dispose();m.material?.dispose();});this.animals.delete(id);}for(const a of W.animals)if(live.has(a.id)){let q=this.animals.get(a.id);if(!q){q=makeAnimal(a);this.animals.set(a.id,q);this.scene.add(q.g);}q.a=a;if(a.adrift&&!q.raft)q.raft=box(q.g,'#a5834e',0,-.10,0,1.1,.1,1.3);if(q.raft)q.raft.visible=!!a.adrift;}}
 animate(seconds,f){const W=this.W;this.human.animate(W,seconds,f);for(const q of this.animals.values()){const {a,g}=q,p=a.trail?along(a.trail,f,a.x,a.y):{x:(a.px??a.x)+(a.x-(a.px??a.x))*f,y:(a.py??a.y)+(a.y-(a.py??a.y))*f,dx:a.x-(a.px??a.x),dy:a.y-(a.py??a.y),distance:Math.hypot(a.x-(a.px??a.x),a.y-(a.py??a.y))*2};let height=groundAt(W,p.x*2,p.y*2);g.rotation.set(0,Math.hypot(p.dx,p.dy)>.001?Math.atan2(p.dx,p.dy):(a.face||1)*Math.PI/2,0);
   if(a.adrift||a.act==='swim'){const ocean=waterAt(W,p.x*2,p.y*2,seconds);height=ocean.h+.12;floatOrientation(g,ocean,g.rotation.y);}else if(a.air)height+=1.2;const size=clamp(Math.cbrt((a.body?.mass||1)/(a.sp==='rabbit'?1.5:a.sp==='gull'?.9:18)),.2,1.3);g.scale.setScalar(size);g.position.set(p.x*2,height,p.y*2);const asleep=['sleep','lie','curl','roost'].includes(a.act),phase=seconds*(p.distance/60)/Math.max(.15,a.sp==='dog'?.55:.25)*Math.PI*2;g.scale.y=size*(asleep&&a.sp==='dog'&&!a.adrift?.4:1);
   for(let n=0;n<q.legs.length;n++){const x=n%2?.12:-.12,z=n<2?.25:-.24,y=a.sp==='gull'?.15:a.sp==='rabbit'?.2:.44,lift=asleep?0:Math.max(0,Math.sin(phase+(n%2)*Math.PI))*.09;fit(q.legs[n],new THREE.Vector3(x,y,z),new THREE.Vector3(x,.02+lift,z+(asleep?0:Math.cos(phase+(n%2)*Math.PI)*.05)));}for(let n=0;n<q.wings.length;n++)q.wings[n].rotation.z=a.air?Math.sin(seconds*8+a.id)*(n?1:-1)*.8:0;
  }}
}
