import * as THREE from 'three/webgpu';
import {fitted,MAT} from '../../v2/src/build/assembly.js';
import {groundAt,clamp,seeded,waterAt} from './model.js';
import {shipXY} from '../../v2/src/sim/ships.js';
const palette={poles:'#9c7548',withies:'#ad8b58',reeds:'#b5a061',bracken:'#a6874c',boughs:'#566d41',debris:'#84643e',mud:'#9b6950',stones:'#8f9487'};
const unitY=new THREE.Vector3(0,1,0);
const stageFraction=(s,n)=>s.stage>n?1:s.stage===n?clamp(s.prog||0):0;
const circularRadius=(kg,density,length)=>Math.sqrt(Math.max(0,kg)/density/(Math.PI*length));
export function material(c,roughness=.82){return new THREE.MeshStandardNodeMaterial({color:c,roughness});}
export function ball(parent,c,x,y,z,sx,sy,sz,detail=1){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(1,detail),typeof c==='string'?material(c):c);m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.castShadow=m.receiveShadow=true;parent.add(m);return m;}
export function box(parent,c,x,y,z,w,h,d){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),typeof c==='string'?material(c):c);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;parent.add(m);return m;}
export function bar(parent,c,a,b,r){const v=new THREE.Vector3().subVectors(b,a),m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,v.length(),8),typeof c==='string'?material(c):c);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(unitY,v.normalize());m.castShadow=m.receiveShadow=true;parent.add(m);return m;}
export function floatOrientation(g,p,heading){g.quaternion.setFromUnitVectors(unitY,new THREE.Vector3(-p.nx,1,-p.ny).normalize()).multiply(new THREE.Quaternion().setFromAxisAngle(unitY,heading));}
function disposeGroup(g){const materials=new Set();g.traverse(m=>{m.geometry?.dispose();if(m.material)materials.add(m.material);});for(const m of materials)m.dispose();g.removeFromParent();}
function quad(parent,points,mat,f){const p=points.map(v=>new THREE.Vector3(v[0],v[2],v[1]));p[1].lerpVectors(p[0],p[1],f);p[2].lerpVectors(p[3],p[2],f);const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute([p[0],p[1],p[2],p[0],p[2],p[3]].flatMap(v=>v.toArray()),3));geometry.computeVertexNormals();mat.side=THREE.DoubleSide;const mesh=new THREE.Mesh(geometry,mat);mesh.castShadow=mesh.receiveShadow=true;parent.add(mesh);return mesh;}
export class Objects {
 constructor(scene,W){this.scene=scene;this.group=new THREE.Group();scene.add(this.group);this.drifters=[];this.fires=[];this.ships=[];this.update(W);}
 update(W){this.W=W;for(const m of [...this.group.children])disposeGroup(m);this.drifters=[];this.fires=[];this.ships=[];
  for(const s of W.structs){const group=new THREE.Group();group.userData={kind:'structure',id:s.id};group.position.set(s.x*2,groundAt(W,s.x*2,s.y*2),s.y*2);group.rotation.y=-(s.dir||0)*Math.PI/2;this.group.add(group);
   if(s.assembly)for(const p of s.assembly.parts){const f=fitted(s,p);if(f<=0)continue;const mat=material(palette[p.mat]||'#968468',.65+(s.saturation||0)*.25);mat.color.multiplyScalar(.72+.28*(p.condition??1));
    if(p.kind==='bar'){const a=s.assembly.nodes[p.a],b=s.assembly.nodes[p.b],len=Math.hypot(...a.map((v,i)=>b[i]-v)),r=Math.sqrt(p.amount*MAT[p.mat].kg/MAT[p.mat].density/(Math.PI*Math.max(.01,len))),point=t=>new THREE.Vector3(a[0]+(b[0]-a[0])*t,a[2]+(b[2]-a[2])*t-(p.sag||0)*4*t*(1-t),a[1]+(b[1]-a[1])*t);for(let n=0;n<4;n++){const m=bar(group,mat,point(f*n/4),point(f*(n+1)/4),r);m.userData.shared=true;}}
    else if(p.kind==='panel'){quad(group,p.points,mat,f);}
    else if(p.kind==='joint'){const p0=s.assembly.nodes[p.node];if(p0)ball(group,mat,p0[0],p0[2],p0[1],.06,.045,.06);}
    else if(p.kind==='shell'){const [x,z,y]=p.center,[w,d,h]=p.size;const thick=Math.min(.08,Math.max(.005,p.amount*MAT[p.mat].kg/MAT[p.mat].density/Math.max(.01,2*(w*h+d*h)+w*d)));box(group,mat,x,y,z,w,thick,d);box(group,mat,x-w/2,y+h/2,z,thick,h*f,d);box(group,mat,x+w/2,y+h/2,z,thick,h*f,d);box(group,mat,x,y+h/2,z-d/2,w,h*f,thick);box(group,mat,x,y+h/2,z+d/2,w,h*f,thick);}
    else if(p.kind==='stock'){const [x,z,y]=p.center||[0,0,0],volume=p.amount*f*MAT[p.mat].kg/MAT[p.mat].density,r=Math.cbrt(volume);ball(group,mat,x,y+r/2,z,r,r/2,r);}
   }else{const f=stageFraction(s,0),stoneR=Math.cbrt(3*MAT.stones.kg/(4*Math.PI*MAT.stones.density));
    if(s.k==='fireRing')for(let n=0;n<Math.ceil(10*f);n++){const angle=n*Math.PI/5,scale=Math.cbrt(clamp(10*f-n));ball(group,'#8d8b7a',Math.cos(angle)*.45,stoneR*scale,Math.sin(angle)*.45,stoneR*scale,stoneR*scale,stoneR*scale);}
    if(s.k==='reflector')for(let n=0;n<Math.ceil(6*f);n++){const installed=clamp(6*f-n),r=circularRadius(MAT.poles.kg*installed,MAT.poles.density,1.4);bar(group,'#94774c',new THREE.Vector3(-.7,.035+n*.065,0),new THREE.Vector3(.7,.035+n*.065,0),r);}
    if(s.k==='snare'&&f>0){const pegKg=.1*MAT.withies.kg*3*f,r=circularRadius(pegKg,MAT.withies.density,.42);bar(group,'#94774c',new THREE.Vector3(0,0,0),new THREE.Vector3(0,.42,0),r);const ropeVolume=.9*MAT.withies.kg*3*f/MAT.withies.density,loop=new THREE.Mesh(new THREE.TorusGeometry(.11,Math.sqrt(ropeVolume/(2*Math.PI*Math.PI*.11)),6,24),material('#cbb883'));loop.position.set(0,.17,.09);group.add(loop);}
    if(s.k==='fishTrap'&&f>0){for(let k=0;k<12;k++){const a=k*Math.PI/6,A=new THREE.Vector3(Math.cos(a)*.25,.07,Math.sin(a)*.25),B=new THREE.Vector3(Math.cos(a)*.17,.65,Math.sin(a)*.17);bar(group,'#af955e',A,B,circularRadius(15*MAT.withies.kg*f/12,MAT.withies.density,A.distanceTo(B)));}const set=stageFraction(s,1);for(let n=0;n<Math.ceil(4*set);n++){const a=n*Math.PI/2,r=stoneR*Math.cbrt(clamp(4*set-n));ball(group,'#8d8b7a',Math.cos(a)*.2,r,Math.sin(a)*.2,r,r,r);}}
    if(s.k==='woodpile'&&f>0){const r=circularRadius(MAT.poles.kg*f,MAT.poles.density,1.6);for(const z of [-.3,.3])bar(group,'#88623c',new THREE.Vector3(-.8,.12,z),new THREE.Vector3(.8,.12,z),r);const cover=stageFraction(s,1),key=s.stages[1]&&Object.keys(s.stages[1].need)[0];if(cover>0&&MAT[key]){const volume=(s.stages[1].need[key]||0)*MAT[key].kg*cover/MAT[key].density;box(group,palette[key],0,.62,0,1.6,volume/1.6/.8,.8);}}
    if(s.k==='signal'&&f>0){const amount=4*MAT.poles.kg*f;for(let n=0;n<3;n++){const a=n*Math.PI*2/3,A=new THREE.Vector3(Math.cos(a)*.45,0,Math.sin(a)*.45),B=new THREE.Vector3(0,1.5,0);bar(group,'#88623c',A,B,circularRadius(amount/3,MAT.poles.density,A.distanceTo(B)));}const mass=9*MAT.boughs.kg*stageFraction(s,1);if(mass>0){const r=Math.cbrt(3*mass/(4*Math.PI*MAT.boughs.density));ball(group,palette.boughs,0,r,0,r,r,r);}}
    // Earthworks already move the finite terrain relief: no duplicate soil box.
   }
   let at=0;for(const [k,n]of Object.entries(s.onsite||{})){if(n<=.001||!MAT[k])continue;const r=Math.cbrt(n*MAT[k].kg/MAT[k].density);ball(group,palette[k],(at++%3)*.5-.8,r/3,-.8,r*.8,r/3,r*.6);}
  }
  // Downed items are finite saved masses. Instancing keeps an old island cheap.
  const items=W.items.filter(q=>q.k==='branch'||q.k==='scraps'||q.k==='quarry'),geo=new THREE.CylinderGeometry(1,1,1,6),mat=material('#76583c'),mesh=new THREE.InstancedMesh(geo,mat,Math.max(1,items.length)),o=new THREE.Object3D();mesh.count=items.length;mesh.castShadow=mesh.receiveShadow=true;mesh.userData={kind:'items'};
  for(let n=0;n<items.length;n++){const q=items[n],len=q.len||Math.max(.2,(q.kg||.5)*.8),r=Math.sqrt(Math.max(.001,q.kg||.2)/650/Math.PI/len);o.position.set(q.x*2,groundAt(W,q.x*2,q.y*2)+r,q.y*2);o.rotation.set(Math.PI/2,seeded(q.id,3,W.seed)*Math.PI*2,0);o.scale.set(r,len,r);o.updateMatrix();mesh.setMatrixAt(n,o.matrix);}mesh.computeBoundingSphere();this.group.add(mesh);
  for(const F of W.fires){const g=new THREE.Group();g.position.set(F.x*2,groundAt(W,F.x*2,F.y*2),F.y*2);this.group.add(g);const kg=Object.values(F.fuel).reduce((n,f)=>n+f[0],0),count=Math.min(8,Math.ceil(kg));for(let n=0;n<count;n++){const a=n*Math.PI/4,A=new THREE.Vector3(Math.cos(a)*.3,.05,Math.sin(a)*.3),B=new THREE.Vector3(-Math.cos(a)*.3,.13,-Math.sin(a)*.3);bar(g,'#5a3e29',A,B,circularRadius(kg/count,MAT.poles.density,A.distanceTo(B)));}
   const emberMat=new THREE.MeshStandardNodeMaterial({color:'#593726',emissive:'#dc4f17',emissiveIntensity:Math.min(4,(F.embers||0)*6),roughness:.9});ball(g,emberMat,0,.04,0,.24,.025,.22);
   if(F.lit){const flameMat=new THREE.MeshBasicNodeMaterial({color:'#ffb94e',transparent:true,opacity:.5,depthWrite:false});const flame=new THREE.Mesh(new THREE.ConeGeometry(.12,.5,7,2,true),flameMat);flame.position.y=.27;g.add(flame);this.fires.push({F,flame});}
  }
  for(const q of W.ocean.drifters||[]){const g=new THREE.Group();bar(g,'#7f6846',new THREE.Vector3(-(q.len||1)/2,0,0),new THREE.Vector3((q.len||1)/2,0,0),Math.sqrt(Math.max(.01,q.kg||.5)/650/Math.PI/(q.len||1)));this.group.add(g);this.drifters.push({q,g});}
  for(const sh of W.ships){const g=new THREE.Group(),p=shipXY(W,sh),coaster=sh.k==='coaster',length=coaster?45:sh.k==='yacht'?12:20;box(g,'#595d57',0,0,0,4,2,length);box(g,'#c4c2af',0,2,-length*.2,3,3,5);if(sh.k==='yacht'){bar(g,'#c4b894',new THREE.Vector3(0,1,0),new THREE.Vector3(0,12,0),.12);quad(g,[[-.1,0,1],[-.1,0,12],[-.1,4,2],[-.1,4,1]],material('#e7debd'),1);}g.position.set(W.cx*2+p.x,0,W.cy*2+p.y);const heading=sh.side%2?0:Math.PI/2;g.rotation.y=heading;g.userData={kind:'ship',id:sh.id};this.group.add(g);this.ships.push({g,heading});}
 }
 animate(seconds){for(const {q,g}of this.drifters){const p=waterAt(this.W,q.x*2,q.y*2,seconds);g.position.set(q.x*2,p.h,q.y*2);floatOrientation(g,p,seeded(q.id,9,this.W.seed)*Math.PI*2);}for(const {g,heading}of this.ships){const p=waterAt(this.W,g.position.x,g.position.z,seconds);g.position.y=p.h;floatOrientation(g,p,heading);}for(const {F,flame}of this.fires){const height=Math.max(.03,.15*Math.pow(F.heat/1000,.4));flame.scale.set(1,height/.5,1);flame.position.y=height/2+.06;const velocity=new THREE.Vector3(this.W.wx.u||0,Math.max(.1,Math.sqrt(9.81*height)),this.W.wx.v||0).normalize();flame.quaternion.setFromUnitVectors(unitY,velocity);}}
}
