import * as THREE from 'three/webgpu';
import {groundAt,seeded,clamp} from './model.js';
const treeKinds=new Set(['oak','pine','birch','rowan','hazel']);
export class Vegetation {
 constructor(scene,W){this.ents=W.ents;this.trunkIds=[];this.leafIds=[];this.rockIds=[];this.object=new THREE.Object3D();const count=W.ents.length;
 this.trunks=new THREE.InstancedMesh(new THREE.CylinderGeometry(.1,.17,1,7),new THREE.MeshStandardNodeMaterial({color:'#74513b',roughness:.9}),count);this.leaves=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,1),new THREE.MeshStandardNodeMaterial({color:'#ffffff',roughness:.9}),count*5);this.rocks=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,1),new THREE.MeshStandardNodeMaterial({color:'#98988a',roughness:1}),count);for(const m of [this.trunks,this.leaves,this.rocks]){m.castShadow=m.receiveShadow=true;scene.add(m);}
 const grassCount=W.ter.reduce((n,t)=>n+([3,4,5,8].includes(t)?3:0),0);this.grass=new THREE.InstancedMesh(new THREE.ConeGeometry(.08,.35,3),new THREE.MeshStandardNodeMaterial({color:'#809059',roughness:1}),grassCount);this.grass.receiveShadow=true;scene.add(this.grass);this.update(W);}
 update(W){let t=0,l=0,r=0,g=0;const o=this.object,color=new THREE.Color();this.trunkIds=[];this.leafIds=[];this.rockIds=[];
 for(let k=0;k<W.ents.length;k++){const e=W.ents[k],x=e.x*2,z=e.y*2,y=groundAt(W,x,z),size=e.size||.6;if(treeKinds.has(e.k)){
 const h=(e.k==='hazel'?2.4:e.k==='pine'?8:6.5)*size;o.position.set(x,y+h/2,z);o.scale.set(size,h,size);o.rotation.set(0,seeded(e.id,4,W.seed)*6.28,0);o.updateMatrix();this.trunks.setMatrixAt(t,o.matrix);this.trunks.setColorAt(t,new THREE.Color(e.k==='birch'?'#cec9af':'#74513b'));this.trunkIds[t++]=e.id;
 const live=clamp((e.leafKg??8)/8)*(1-(e.fall||0)*.9),aut=e.aut||0;for(let j=0;j<5;j++){const radius=(e.k==='hazel'?.8:1.55)*size,angle=j*2.4;let px=x+Math.cos(angle)*radius*.65,pz=z+Math.sin(angle)*radius*.65,py=y+h*(.6+j*.06);o.position.set(px,py,pz);o.scale.set(radius*(.85+seeded(e.id,j,W.seed)*.4)*Math.sqrt(live),radius*(e.k==='pine'?1.3:.85)*Math.sqrt(live),radius*Math.sqrt(live));o.rotation.set(0,angle,0);o.updateMatrix();this.leaves.setMatrixAt(l,o.matrix);color.set(e.k==='pine'?'#365c47':e.k==='birch'?'#8ea452':'#71894b');if(e.k!=='pine')color.lerp(new THREE.Color(j%2?'#b88a3d':'#a96d32'),aut);color.multiplyScalar(.85+seeded(e.id,j+50,W.seed)*.3);this.leaves.setColorAt(l,color);this.leafIds[l++]=e.id;}
 }else if(['boulder','flint','stones'].includes(e.k)){o.position.set(x,y+size*.5,z);o.scale.set(size*.9,size*.7,size);o.rotation.set(.2,seeded(e.id,2,W.seed)*6.28,.1);o.updateMatrix();this.rocks.setMatrixAt(r,o.matrix);this.rockIds[r++]=e.id;}
 else {for(let j=0;j<3;j++){o.position.set(x+(j-1)*.25,y+.2,z+Math.sin(j)*.25);o.scale.set(size*.55,size*.4,size*.55);o.rotation.set(0,j,0);o.updateMatrix();this.leaves.setMatrixAt(l,o.matrix);this.leaves.setColorAt(l,new THREE.Color(e.k==='gorse'?'#879143':e.k==='reeds'?'#99935c':'#617748'));this.leafIds[l++]=e.id;}}
 }
 this.trunks.count=t;this.leaves.count=l;this.rocks.count=r;for(const m of [this.trunks,this.leaves,this.rocks]){m.instanceMatrix.needsUpdate=true;if(m.instanceColor)m.instanceColor.needsUpdate=true;m.computeBoundingSphere();}
 for(let i=0;i<W.ter.length;i++)if([3,4,5,8].includes(W.ter[i]))for(let j=0;j<3;j++){const x=(i%W.MW+seeded(i,j,W.seed))*2,z=(Math.floor(i/W.MW)+seeded(i,j+7,W.seed))*2,mass=W.foodweb.grass[i]||0;o.position.set(x,groundAt(W,x,z)+.1,z);o.rotation.set(0,j,0);o.scale.set(1,clamp(mass/.03,0,1.4),1);o.updateMatrix();this.grass.setMatrixAt(g++,o.matrix);}this.grass.count=g;this.grass.instanceMatrix.needsUpdate=true;this.grass.computeBoundingSphere();}
 pick(mesh,id,W){const ids=mesh===this.trunks?this.trunkIds:mesh===this.leaves?this.leafIds:mesh===this.rocks?this.rockIds:[];return W.ents.find(e=>e.id===ids[id]);}
}
