import * as THREE from 'three/webgpu';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {Terrain,MarineBed,freshwater} from './terrain.js';
import {Vegetation} from './vegetation.js';
import {Ocean} from './ocean.js';
import {Lighting} from './lighting.js';
import {Objects} from './objects.js';
import {Actors} from './actors.js';
import {Weather} from './weather.js';
import {makePost} from './post.js';
import {groundAt,waterAt,clamp} from './model.js';
import {displaySeconds} from '../../v2/src/render/simulation-clock.js';
export class View {
 constructor(canvas,W,settings,onPick,onFailure){this.canvas=canvas;this.W=W;this.settings=settings;this.onPick=onPick;this.onFailure=onFailure;this.frames=0;this.follow=false;this.keys=new Set();this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(43,1,.12,24000);this.renderer=new THREE.WebGPURenderer({canvas,antialias:true,powerPreference:'high-performance',outputBufferType:THREE.FloatType});this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFShadowMap;this.renderer.toneMapping=THREE.AgXToneMapping;
  this.controls=new OrbitControls(this.camera,canvas);this.controls.enableDamping=true;this.controls.dampingFactor=.08;this.controls.maxPolarAngle=Math.PI*.48;this.controls.minDistance=3;this.controls.maxDistance=900;this.controls.enablePan=true;this.controls.screenSpacePanning=false;this.controls.target.set(W.MW,3,W.MH);this.camera.position.set(W.MW+90,110,W.MH+155);this.controls.update();
  this.controls.addEventListener('start',()=>{this.follow=false;});this.ray=new THREE.Raycaster();this.pointer=new THREE.Vector2();
  let down;canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};});canvas.addEventListener('pointerup',e=>{if(e.button===0&&down&&Math.hypot(down.x-e.clientX,down.y-e.clientY)<5)this.pick(e.clientX,e.clientY);down=null;});
  this.resize=()=>{this.renderer.setPixelRatio(Math.min(devicePixelRatio,this.settings.quality==='ultra'?2:1.5)*this.settings.scale);this.renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);this.camera.aspect=canvas.clientWidth/canvas.clientHeight;this.camera.updateProjectionMatrix();};addEventListener('resize',this.resize);this.resize();
 }
 async init(){await this.renderer.init();this.backend=this.renderer.backend.isWebGPUBackend?'WebGPU':'WebGL2';this.gpuFailure=e=>{if(!this.running)return;this.running=false;cancelAnimationFrame(this.raf);this.onFailure(e.error||Error(e.message||'The graphics device stopped.'));};this.renderer.backend.device?.addEventListener('uncapturederror',this.gpuFailure);this.terrain=new Terrain(this.scene,this.W);this.marineBed=new MarineBed(this.scene,this.W);this.fresh=freshwater(this.scene,this.W);this.vegetation=new Vegetation(this.scene,this.W);this.ocean=new Ocean(this.scene,this.W,this.settings.quality);this.objects=new Objects(this.scene,this.W);this.actors=new Actors(this.scene,this.W);this.weather=new Weather(this.scene);this.weather.update(this.W);this.lighting=new Lighting(this.scene,this.renderer,this.W,this.settings.quality);this.post=makePost(this.renderer,this.scene,this.camera,this.settings.quality);this.previous=performance.now();this.anchorClock(this.W);this.start();return this;}
 anchorClock(W){const seconds=(Date.now()-W.born)/1000,now=performance.now(),fraction=Math.floor(seconds/60)===W.t?clamp(seconds-W.t*60,0,60):0;displaySeconds(W,now-fraction*1000);}
 update(W){this.W=W;this.anchorClock(W);for(const q of [this.terrain,this.marineBed,this.fresh,this.vegetation,this.ocean,this.objects,this.actors,this.weather,this.lighting])q.update(W);}
 quality(q){this.settings.quality=q;this.ocean.dispose();this.ocean=new Ocean(this.scene,this.W,q);this.lighting.quality(q);this.post.dispose();this.post=makePost(this.renderer,this.scene,this.camera,q);this.resize();}
 start(){this.running=true;this.lastDraw=performance.now();if(!this.lossWatched&&this.renderer.backend.device){this.lossWatched=true;this.renderer.backend.device.lost.then(info=>{if(!this.disposed)this.gpuFailure({error:Error(info.message||'The graphics device was lost. Restart the view to reconnect it.')});});}const draw=now=>{if(!this.running)return;this.raf=requestAnimationFrame(draw);const gap=1000/this.settings.fps,elapsed=now-this.previous;if(elapsed<gap)return;const dt=Math.min(1,(now-this.lastDraw)/1000);this.lastDraw=now;this.previous=now-elapsed%gap;try{this.draw(now,dt);this.frames++;}catch(e){this.running=false;cancelAnimationFrame(this.raf);this.onFailure(e);}};this.raf=requestAnimationFrame(draw);}
 draw(now,dt){const W=this.W,seconds=displaySeconds(W,now),fraction=clamp((seconds-W.t*60)/60);this.seconds=seconds;this.actors.animate(seconds,fraction);if(this.follow){const q=this.actors.human.root.position,delta=q.clone().sub(this.controls.target);this.controls.target.copy(q);this.camera.position.add(delta);}this.keyboard(Math.min(.1,dt));this.controls.update();this.ocean.animate(seconds);this.objects.animate(seconds);this.weather.animate(seconds,this.controls.target);this.lighting.exposureCompensation=2**this.settings.exposure;this.lighting.animate(seconds,this.camera,this.controls.target,dt);this.renderer.info.reset();this.post.render();}
 keyboard(dt){if(!this.keys.size)return;const speed=this.camera.position.distanceTo(this.controls.target)*dt*.65,forward=new THREE.Vector3().subVectors(this.controls.target,this.camera.position);forward.y=0;forward.normalize();const right=new THREE.Vector3().crossVectors(forward,new THREE.Vector3(0,1,0)),delta=new THREE.Vector3();if(this.keys.has('w'))delta.addScaledVector(forward,speed);if(this.keys.has('s'))delta.addScaledVector(forward,-speed);if(this.keys.has('a'))delta.addScaledVector(right,-speed);if(this.keys.has('d'))delta.addScaledVector(right,speed);if(delta.length()){this.follow=false;this.camera.position.add(delta);this.controls.target.add(delta);}const angle=(this.keys.has('q')?1:0)-(this.keys.has('e')?1:0);if(angle){const offset=this.camera.position.clone().sub(this.controls.target);offset.applyAxisAngle(new THREE.Vector3(0,1,0),angle*dt);this.camera.position.copy(this.controls.target).add(offset);}}
 focus(kind){const W=this.W;let x=W.man.x*2,z=W.man.y*2,dist=22;if(kind==='island'){x=W.MW;z=W.MH;dist=220;}if(kind==='camp'){const s=W.structs.find(s=>s.id===W.camp)||W.structs.find(s=>s.assembly?.habitat);if(s){x=s.x*2;z=s.y*2;}dist=25;}if(kind==='ocean'){const i=W.ter.findIndex((t,i)=>t<=1&&W.ocean.coastBed[i]>-6&&i%W.MW>4&&i%W.MW<W.MW-5&&Math.floor(i/W.MW)>4);if(i>=0){x=(i%W.MW+.5)*2;z=(Math.floor(i/W.MW)+.5)*2;}else{x=30;z=30;}const away=new THREE.Vector2(x-W.MW,z-W.MH).normalize(),surface=waterAt(W,x,z,this.seconds??W.t*60).h;this.controls.target.set(x+away.x*22,surface,z+away.y*22);this.camera.position.set(x-away.x*10,surface+5,z-away.y*10);this.follow=false;this.controls.update();return;}const y=groundAt(W,x,z);this.controls.target.set(x,Math.max(0,y)+.6,z);this.camera.position.set(x+dist*.55,Math.max(0,y)+dist*.68,z+dist*.85);this.follow=kind==='man';this.controls.update();}
 pick(clientX,clientY){const r=this.canvas.getBoundingClientRect();this.pointer.set((clientX-r.left)/r.width*2-1,-((clientY-r.top)/r.height*2-1));this.ray.setFromCamera(this.pointer,this.camera);const hits=this.ray.intersectObjects(this.scene.children,true).filter(h=>!['weather','ocean'].includes(h.object.userData.kind)),ray=this.ray.ray;
  // CPU mesh intersections see the undisplaced source plane. Solve the same
  // observed height field along the camera ray, then sort with real land hits.
  if(ray.direction.y<-.0001){let distance=-ray.origin.y/ray.direction.y;for(let n=0;n<10;n++){const p=ray.at(distance,new THREE.Vector3()),q=waterAt(this.W,p.x,p.z,this.seconds??this.W.t*60,this.ocean.spacing),f=p.y-q.h,derivative=ray.direction.y-q.nx*ray.direction.x-q.ny*ray.direction.z;if(Math.abs(derivative)<1e-6)break;distance-=clamp(f/derivative,-20,20);if(Math.abs(f)<.001)break;}const point=ray.at(distance,new THREE.Vector3()),q=waterAt(this.W,point.x,point.z,this.seconds??this.W.t*60,this.ocean.spacing);if(distance>0&&q.wet>.001&&Math.abs(point.y-q.h)<.02&&point.y>groundAt(this.W,point.x,point.z)+.005)hits.push({distance,point,object:{userData:{kind:'ocean'}}});}hits.sort((a,b)=>a.distance-b.distance);
  for(const hit of hits){let object=hit.object;const e=this.vegetation.pick(object,hit.instanceId,this.W);if(e){this.onPick({kind:'entity',id:e.id});return;}while(object&&!object.userData.kind)object=object.parent;if(!object)continue;const kind=object.userData.kind;if(kind==='terrain'||kind==='items')return;if(kind==='ocean'){this.onPick({kind,x:hit.point.x/2,y:hit.point.z/2});return;}if(kind==='puddles'){this.onPick({kind:'freshwater',tile:object.userData.tiles[hit.instanceId]});return;}if(['structure','man','animal','ship','freshwater'].includes(kind)){this.onPick(object.userData);return;}}
 }
 diagnostics(){return{backend:this.backend,frames:this.frames,minute:this.W.t,quality:this.settings.quality,resolution:[this.canvas.width,this.canvas.height],waterVertices:this.ocean.patches.reduce((n,p)=>n+p.mesh.geometry.attributes.position.count,0),sunLux:this.lighting.sunLux,moonLux:this.lighting.moonLux,exposure:this.renderer.toneMappingExposure,drawCalls:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles};}
 dispose(){this.disposed=true;this.running=false;cancelAnimationFrame(this.raf);this.renderer.backend.device?.removeEventListener('uncapturederror',this.gpuFailure);removeEventListener('resize',this.resize);this.controls.dispose();this.scene.traverse(m=>{m.geometry?.dispose();m.material?.dispose();});this.ocean.dispose();this.lighting.dispose();this.post.dispose();this.renderer.dispose();}
}
