import {load,save} from '../../v2/src/sim/world.js';
import {cal,MON} from '../../v2/src/core/time.js';
import {View} from '../render/view.js';
import {audioStart,audioStop,audioUpdate} from '../../v2/src/audio.js';
import {lifeEntries} from '../../v2/src/render/journal.js';
import {inventoryRows,effortRows,batchRows,sensoryRows,structureDetails,animalDetails,oceanDetails,toolDetails} from '../../v2/src/render/inspection.js';
import {oceanSample} from '../../v2/src/sim/ocean.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),number=(n,d=1)=>Number(n||0).toFixed(d),rows=items=>items.map(q=>`<div class="row"><span>${esc(q.label)}</span><span>${esc(q.value)}</span></div>`).join('');
let W,view,creating=false,first=true,target,tab='story',sound=false,online=null,toastTimer,panelFocus;
const defaults={quality:'high',fps:60,scale:1,exposure:0};let stored;try{stored=JSON.parse(localStorage.getItem('castaway-view'));}catch{}const settings={...defaults,...stored};if(!['high','ultra'].includes(settings.quality))settings.quality='high';settings.fps=[60,120,144,240].includes(settings.fps)?settings.fps:60;settings.scale=Math.min(1.5,Math.max(.5,+settings.scale||1));settings.exposure=Math.min(2,Math.max(-2,+settings.exposure||0));
const persistSettings=()=>localStorage.setItem('castaway-view',JSON.stringify(settings));
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
function fail(e){$('loading').hidden=true;$('failure-text').textContent=e.message||String(e);$('failure').hidden=false;console.error(e);}
async function createView(){if(creating||!W)return;creating=true;try{if(view)view.dispose();view=new View($('island'),W,settings,pick,fail);await view.init();if(view.W!==W)view.update(W);$('loading').hidden=true;$('failure').hidden=true;$('status').textContent=`${view.backend} · the island is living`;if(view.backend!=='WebGPU')toast('WebGPU is unavailable; the view is running with WebGL2.');if(first){view.focus('island');first=false;}}catch(e){fail(e);}finally{creating=false;}}
function calendar(t){const c=cal(W.born,t);return `Day ${Math.floor(t/1440)+1} · ${c.wd} ${c.d} ${MON[c.mo]} · ${String(c.h).padStart(2,'0')}:${String(c.mi).padStart(2,'0')} UK`;}
function refresh(){const M=W.man,x=W.wx;$('calendar').textContent=calendar(W.t);const description=x.fog>.3?'Fog over the island':x.rain>.4?(x.temp<1?'Snow falling':'Rain moving through'):x.cloud>.7?'Cloud over the island':x.elev<0?'Night on the island':'A little clear sky';$('weather-text').textContent=description;$('weather-icon').textContent=x.rain>.4?'☂':x.elev<0?'☾':x.cloud>.7?'≋':'☼';$('weather-detail').textContent=`${number(x.temp)} °C · ${number(x.wind)} m/s wind${x.rain>.01?' · '+number(x.rain,2)+' mm/h':''}`;
 $('doing').textContent=!M.B.alive?'His life on the island has ended':M.B.asleep?'Sleeping':M.doing||M.act?.a?.replaceAll('_',' ')||'Taking a moment';$('reason').textContent=M.why||M.goal||'';const thought=M.thought||M.say;$('thought').textContent=thought?`“${thought}”`:'';$('thought').hidden=!thought;$('body-state').textContent=!M.B.alive?M.B.cause:M.B.core<35?'Feeling the cold':M.B.ill>.2?'Recovering from illness':M.B.fatigue>.7?'In need of rest':'Going about his life';$('connection').textContent=online===false?'Offline · saved locally':online===true?'Thought feed connected':'Local world';if(target)drawPanel();
}
function pick(t){target=t;openPanel();drawPanel();}
function openPanel(){if($('panel').hidden)panelFocus=document.activeElement;$('panel').hidden=false;view?.keys.clear();$('panel-close').focus();}
function closePanel(){target=null;$('panel').hidden=true;$('panel-tabs').hidden=true;if(panelFocus?.isConnected)panelFocus.focus({preventScroll:true});}
function stamp(t){return calendar(t);}
function journal(){target={kind:'journal'};openPanel();drawPanel();}
function drawPanel(){const M=W.man,p=$('panel-content'),scroll=p.scrollTop;let title='',body='';$('panel-tabs').hidden=true;$('panel-kicker').textContent='THE CASTAWAY';
 if(target.kind==='journal'){title='His life, as it unfolds';$('panel-kicker').textContent='TOMAS’S JOURNAL';$('panel-tabs').hidden=false;$('panel-tabs').innerHTML=['story','words','camp'].map(k=>`<button data-tab="${k}" class="${tab===k?'active':''}">${k==='story'?'His life':k==='words'?'His words':'His camp'}</button>`).join('');if(tab==='story')body=lifeEntries(W).map(e=>`<article class="entry"><time>${stamp(e.t)}</time><p>${esc(e.text)}</p></article>`).join('')||'<p>The first pages are still being lived.</p>';if(tab==='words')body=(M.journal||[]).slice().reverse().map(e=>`<article class="entry"><time>${stamp(e.t)}</time><p>${esc(e.text).replaceAll('\n','<br>')}</p></article>`).join('')||'<p>He has not written in his journal yet.</p>';if(tab==='camp')body=camp();
 }else if(target.kind==='structure'){const s=W.structs.find(s=>s.id===target.id);if(!s){closePanel();return;}const d=structureDetails(s);title=d.title;body=rows(d.fields)+'<h3>Installed materials</h3>'+rows(d.materials)+(d.onsite.length?'<h3>At the site</h3>'+rows(d.onsite):'');if(d.comparison)body+='<h3>His design choices</h3><p>He compared '+esc(d.comparison.alternatives)+' assemblies before choosing this one.</p>'+rows(d.comparison.choices.map((q,i)=>({label:i?'Alternative':'Chosen',value:`${q.cover||'open frame'} · ${Math.round(q.labourMinutes)} min · ${number(q.predictedKg)} kg estimated load`})));
 }else if(target.kind==='tool'){const d=toolDetails(M,target.key);title=d.title;body=rows(d.fields)+'<h3>Working parts</h3>'+rows(d.materials);
 }else if(target.kind==='animal'){const a=W.animals.find(a=>a.id===target.id);if(!a){closePanel();return;}const d=animalDetails(a);title=d.title;body=rows(d.fields);
 }else if(target.kind==='ocean'){const d=oceanDetails(W,target.x??view.controls.target.x/2,target.y??view.controls.target.z/2),q=oceanSample(W,target.x??view.controls.target.x/2,target.y??view.controls.target.z/2);title=d.title;body=rows(d.fields)+rows([{label:'Salt inventory in this cell',value:`${number(q.g.salt[q.i]+q.g.salt[q.g.n+q.i]+q.g.salt[q.g.n*2+q.i],0)} kg`},{label:'Wave energy dissipated',value:`${number(q.g.breaking[q.i],3)} W/m²`}]);
 }else if(target.kind==='entity'){const e=W.ents.find(e=>e.id===target.id);title=e?.k||'The island';body=rows([{label:'Living tissue',value:`${number(e?.liveKg)} kg`},{label:'Leaf mass',value:`${number(e?.leafKg)} kg`},{label:'Dead wood',value:`${number(e?.deadKg)} kg`},{label:'Autumn progression',value:`${number((e?.aut||0)*100,0)}%`}]);
 }else if(target.kind==='freshwater'){title='Fresh water';body=rows([{label:'Temperature',value:`${number(W.hydro.temp)} °C`},{label:'Lake water',value:`${number(W.hydro.lake)} m³`},{label:'Stream flow',value:`${number(W.hydro.flow,3)} m³/min`},{label:'Salt in the lake',value:`${number(W.hydro.saltLake,3)} kg`}]);
 }else if(target.kind==='ship'){const sh=W.ships.find(s=>s.id===target.id);title=sh?.k||'Out at sea';body=rows([{label:'Speed',value:`${number(sh?.v)} m/s`},{label:'Distance offshore',value:`${number((sh?.off||0)/1000)} km`}]);
 }else if(target.kind==='settings'){title='Make yourself comfortable';$('panel-kicker').textContent='DESKTOP SETTINGS';body=settingsBody();
 }else{title='With Tomas';body=rows([{label:'Body temperature',value:`${number(M.B.core)} °C`},{label:'Fat reserves',value:`${number(M.B.fat)} kg`},{label:'Water deficit',value:`${number(M.B.waterDef)} litres`},{label:'Fatigue',value:`${number(M.B.fatigue*100,0)}%`}])+'<h3>His belongings</h3>'+inventoryRows(M).map(q=>q.tool?`<button class="list-button" data-tool="${esc(q.key)}">${esc(q.label)} <small>Inspect ↗</small></button>`:rows([q])).join('')+'<h3>Carrying & experience</h3>'+rows(effortRows(M))+(M.foodBatches?.length?'<h3>His food</h3>'+rows(batchRows(M)):'')+(sensoryRows(M).length?'<h3>What he noticed</h3>'+rows(sensoryRows(M)):'')+'<h3>His camp</h3>'+camp();}
 $('panel-title').textContent=title;p.innerHTML=body;p.scrollTop=scroll;for(const b of p.querySelectorAll('[data-sid]'))b.onclick=()=>{pick({kind:'structure',id:+b.dataset.sid});};for(const b of p.querySelectorAll('[data-tool]'))b.onclick=()=>pick({kind:'tool',key:b.dataset.tool});for(const b of $('panel-tabs').querySelectorAll('button'))b.onclick=()=>{tab=b.dataset.tab;p.scrollTop=0;drawPanel();};if(target.kind==='settings')bindSettings();
}
function camp(){return W.structs.map(s=>`<button class="list-button" data-sid="${s.id}">${esc(structureDetails(s).title)}<small>${s.stage>=s.stages.length?'Complete':'In progress'} ↗</small></button>`).join('')||'<p>He is still finding a place to call home.</p>';}
function settingsBody(){return `<div class="setting"><label for="quality">Graphics</label><select id="quality"><option value="high" ${settings.quality==='high'?'selected':''}>High · 1 m coastal geometry / 4096 shadows</option><option value="ultra" ${settings.quality==='ultra'?'selected':''}>Ultra · 0.5 m coastal geometry / 8192 shadows</option></select></div><div class="setting"><label for="fps">Frame limit</label><select id="fps">${[60,120,144,240].map(n=>`<option value="${n}" ${settings.fps===n?'selected':''}>${n} frames per second</option>`).join('')}</select></div><div class="setting"><label for="scale">Render scale <span>${Math.round(settings.scale*100)}%</span></label><input id="scale" type="range" min=".5" max="1.5" step=".1" value="${settings.scale}"></div><div class="setting"><label for="exposure">Camera exposure <span>${settings.exposure} EV</span></label><input id="exposure" type="range" min="-2" max="2" step=".1" value="${settings.exposure}"></div><div class="buttons"><button id="fullscreen">Full screen</button><button id="save">Save locally</button><button id="export">Export world</button></div><h3>At your keyboard</h3><div class="keys"><b>W A S D</b>Pan the camera<br><b>Q / E</b>Orbit<br><b>F / C / O / 1</b>Tomas / camp / sea / island<br><b>J / M / H</b>Journal / sound / hide interface<br><b>F11</b>Full screen<br><b>Ctrl + S</b>Save locally</div><h3>This session</h3><div id="diagnostics">${rows([{label:'Renderer',value:view?.backend||'Starting'},{label:'World minute',value:W.t},{label:'Update cadence',value:'One physical minute'}])}</div>`;}
function bindSettings(){$('quality').onchange=async e=>{try{const value=e.target.value;view.quality(value);persistSettings();toast('Graphics updated');}catch(err){fail(err);}};$('fps').onchange=e=>{settings.fps=+e.target.value;persistSettings();};$('scale').oninput=e=>{settings.scale=+e.target.value;e.target.previousElementSibling.lastElementChild.textContent=`${Math.round(settings.scale*100)}%`;view.resize();persistSettings();};$('exposure').oninput=e=>{settings.exposure=+e.target.value;e.target.previousElementSibling.lastElementChild.textContent=`${settings.exposure} EV`;persistSettings();};$('fullscreen').onclick=()=>window.castaway.fullscreen();$('save').onclick=()=>window.castaway.save();$('export').onclick=async()=>{if(await window.castaway.exportSave())toast('World exported');};window.castaway.diagnostics().then(d=>{if(!target||target.kind!=='settings')return;const gpu=d.gpu.gpuDevice?.find(g=>g.active)||d.gpu.gpuDevice?.[0];$('diagnostics').innerHTML+=rows([{label:'Graphics device',value:gpu?.deviceString||gpu?.deviceId||'See system graphics settings'},{label:'Version',value:d.version}]);});}
async function toggleSound(){sound=!sound;$('sound-button').textContent=sound?'Sound on':'Sound off';$('sound-button').setAttribute('aria-pressed',sound);try{if(sound)await audioStart();else audioStop();}catch(e){sound=false;$('sound-button').textContent='Sound off';$('sound-button').setAttribute('aria-pressed','false');toast(e.message);}}
$('panel-close').onclick=closePanel;$('journal-button').onclick=journal;$('man-details').onclick=()=>pick({kind:'man'});$('settings-button').onclick=()=>pick({kind:'settings'});$('sound-button').onclick=toggleSound;$('retry').onclick=()=>{first=false;createView();};$('save-failure').onclick=()=>window.castaway.save();for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>{view?.focus(b.dataset.view);if(b.dataset.view==='ocean')pick({kind:'ocean'});};
addEventListener('keydown',e=>{if(e.key==='F11'){e.preventDefault();window.castaway.fullscreen();return;}if(e.ctrlKey&&e.key.toLowerCase()==='s'){e.preventDefault();window.castaway.save();return;}if(e.key==='Escape'){closePanel();return;}if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||e.ctrlKey||e.altKey)return;const k=e.key.toLowerCase();if(k==='h'){document.body.classList.toggle('ui-hidden');closePanel();}if(k==='j'&&W)journal();if(k==='m')toggleSound();if(['f','c','o','1'].includes(k)&&view){view.focus({f:'man',c:'camp',o:'ocean',1:'island'}[k]);if(k==='o')pick({kind:'ocean'});}if($('panel').hidden&&view&&['w','a','s','d','q','e'].includes(k)){e.preventDefault();view.keys.add(k);}});addEventListener('keyup',e=>view?.keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>view?.keys.clear());
$('panel').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const items=[...$('panel').querySelectorAll('button,input,select')],i=items.indexOf(document.activeElement);if(e.shiftKey&&i===0){e.preventDefault();items.at(-1).focus();}if(!e.shiftKey&&i===items.length-1){e.preventDefault();items[0].focus();}});
document.addEventListener('castaway-audio-error',()=>{sound=false;$('sound-button').textContent='Sound off';$('sound-button').setAttribute('aria-pressed','false');toast('Sound stopped; click Sound to restart it.');});
window.castaway.subscribe(m=>{if(m.type==='snapshot'){try{W=load(m.blob,m.thoughts);refresh();if(view?.terrain&&!creating)view.update(W);else createView();}catch(e){fail(e);}}if(m.type==='progress'){const p=$('progress');p.max=Math.max(1,m.target-m.start);p.value=m.t-m.start;$('loading-text').textContent=`Catching up ${Math.max(0,m.target-m.t)} physical minutes…`;}if(m.type==='connection'){online=m.online;if(W)refresh();}if(m.type==='saved')toast(`World saved at minute ${m.t}`);if(m.type==='error'){toast(m.message);console.error(m.message);}});window.castaway.ready();
setInterval(()=>{if(sound&&W&&view)audioUpdate(W,{cam:{x:view.controls.target.x*8,y:view.controls.target.z*8}});},100);
if(new URL(location.href).searchParams.has('qa'))window.__castawayQA={get view(){return view;},get world(){return W;},save:()=>save(W),focus:k=>view.focus(k),settings,replace:blob=>{W=load(blob,[]);view.update(W);refresh();},diagnostics:()=>view?.diagnostics()};
